In [8]:
"""
데이터 셀렉션 및 필터링 by pandas
"""

import pandas as pd

titanic_df = pd.read_csv('/Users/ijeonghan/dev/jupyter/train.csv')

#DataFrame 뒤의 [] 연산자
print('단일 칼럼 데이터 추출:\n',titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n',titanic_df[['Survived', 'Pclass']].head(3),'\n')
print('[] 안에 숫자 인덱스는 KeyError 오류 발생:\n',titanic_df[0])

단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

In [10]:
#DataFrame의 [] 안에 숫자 값을 입력할 경우 오류 발생, 하지만 인덱스 형태로 변환 가능한 표현식은 입력 가능
titanic_df[0:2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [11]:
#DataFrame의 [] 안에 Boolean indexing
titanic_df[titanic_df['Pclass'] == 3].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [20]:
#ix[], iloc[], loc[] 연산자를 위한 DataFrame 생성
data = {'Name': ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', ' Male', 'Male']
       }

data_df = pd.DataFrame(data, index =['one', 'two', 'three', 'four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [12]:
#ix[행 위치 지정, 열 위치 지정], 칼럼 명칭 기반 or 칼럼 위치 기반 인덱싱 방식 사용 , 혼란 및 가독성 때문에 사용하지 않는 방식(pandas 1.0.0부터 삭제)

#print('칼럼 위치 기반 인덱싱 데이터 추출:',titanic_df.ix[0,2])
#print('칼럼 명칭 기반 인덱싱 데이터 추출:',titanic_df.ix[0,'Pclass'])

AttributeError: 'DataFrame' object has no attribute 'ix'

In [21]:
#새로운 row index 값 생성

data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns ={'index': 'old_index'})

data_df_reset.index = data_df_reset.index + 1
data_df_reset

  old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [16]:
#iloc[] 연산자, 위치 기반 인덱싱을 사용하는 연산자, 단 Boolean indexing은 제공 x

data_df.iloc[0,0]

'Chulmin'

In [17]:
#Error 유발 코드,  column 값에 명칭 기반 인덱싱
data_df.iloc[0,'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [18]:
#Error 유발 코드, row 값에  명칭기반 인덱싱
data_df.iloc['one',0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [28]:
# index가 1부터 시작하는 새로운 정수형 인덱스 값을 가지고 있는 data_df_reset에 iloc적용
data_df_reset.iloc[0,1]

'Chulmin'

In [31]:
#DataFrame loc[] 연산자, 명칭 기반 인덱싱 사용하는 연산자 , [DataFrame's index, columns name]
data_df.loc['one', 'Name']

'Chulmin'

In [32]:
#data_df_reset에 설정한 정수형 인덱스 값 활용(index: 1 ~)
data_df_reset.loc[1,'Name']

'Chulmin'

In [33]:
#다음 코드는 error 발생합니다.
data_df_reset.loc[0,'Name']

KeyError: 0

In [37]:
#명칭 기반 인덱싱, 위치 기반 인덱싱에서 슬라이싱 적용 시 차이점 확인
print('위치 기반 iloc slicing\n', data_df.iloc[0:1,0],'\n')
print('명칭 기반 loc slicing\n', data_df.loc['one':'two', 'Name']) # 명칭 기반 인덱싱에서 슬라이싱은 종료점을 포함한 위치를 반환

위치 기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object

명칭 기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

In [38]:
#Boolean indexing
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean.head()

<class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S

In [50]:
#Boolean indexing에서 원하는 칼럼 별도 추출하기
titanic_df[titanic_df['Age'] > 60][['Name', 'Age']].head()

                               Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [44]:
#Boolean indexing에서 loc 연산자를 통해 칼럼 별도 추출하기
titanic_df.loc[titanic_df['Age'] > 60, ['Name', 'Age']].head()

                               Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [51]:
#여러 조건들을 결합하여 데이터 추출하기 - 나이 60세 이상, 선실 1등급, 성별 여성
titanic_df[(titanic_df['Age'] > 60) & (titanic_df['Pclass'] == 1)&
          (titanic_df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN

In [47]:
#여러 조건들을 결합하여 데이터 추출하기2
cond1 = titanic_df['Age'] > 60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'

titanic_df[cond1 & cond2 & cond3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN